export const TAXONOMIES_REQUEST = "TAXONOMIES_REQUEST"
export const TAXONOMIES_SUCCESS = "TAXONOMIES_SUCCESS"
export const TAXONOMIES_FAILURE = "TAXONOMIES_FAILURE"

export const CATEGORIES_REQUEST = "CATEGORIES_REQUEST"
export const CATEGORIES_SUCCESS = "CATEGORIES_SUCCESS"
export const CATEGORIES_FAILURE = "CATEGORIES_FAILURE"

export const POST_REQUEST = "POST_REQUEST"
export const POST_SUCCESS = "POST_SUCCESS"
export const POST_FAILURE = "POST_FAILURE"
